# Generated by Django 4.2.26 on 2025-11-15 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('links', models.TextField(blank=True, help_text='LinkedIn, GitHub, Portfolio (one per line)')),
                ('summary', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated or grouped')),
                ('experience', models.TextField(blank=True, help_text='JSON format')),
                ('education', models.TextField(blank=True, help_text='JSON format')),
                ('projects', models.TextField(blank=True, help_text='JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_app.cvtemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
